<!-- .tpl prevents Live Server from injecting reload scripts into fetched partials. -->
<!-- Handoff: query audit_logs by the current operator_company_id scope. before_data and after_data belong in a protected detail view, not the compact list. -->
<div class="company-panel__heading"><div><h3>操作记录</h3><p>查看本公司范围内的重要操作和执行结果。</p></div></div>
<section class="content-card company-activity-card" aria-label="公司操作记录列表">
  <form class="filter-bar" action="#" data-company-activity-filter>
    <label class="search-field"><span class="sr-only">搜索操作记录</span><svg class="app-icon app-icon--fill" aria-hidden="true"><use href="icons.svg#icon-search"></use></svg><input type="search" placeholder="搜索操作人、动作或目标" data-company-activity-search></label>
    <label class="select-field"><span class="sr-only">执行结果</span><select data-company-activity-result><option value="">全部结果</option><option value="success">成功</option><option value="failed">失败</option></select><svg class="app-icon app-icon--fill select-field__icon" aria-hidden="true"><use href="icons.svg#icon-chevron-down"></use></svg></label>
  </form>
  <div class="table-scroll company-activity-table" role="region" aria-label="操作记录列表，可横向滚动" tabindex="0">
    <table data-sortable-table><thead><tr><th scope="col">时间</th><th scope="col">操作人</th><th scope="col">模块</th><th scope="col">操作</th><th scope="col">目标</th><th scope="col">结果</th><th scope="col">IP 地址</th><th scope="col" class="table-actions">详情</th></tr></thead><tbody>
      <tr data-company-activity-row data-search="管理员 用户 更新 王工" data-activity-result="success"><td>2026-09-03 10:41</td><td>管理员</td><td>公司用户</td><td>更新用户</td><td>王工</td><td><span class="status status--online">成功</span></td><td class="mono">192.168.1.20</td><td class="table-actions"><button class="icon-button table-action-button" type="button" data-action="view-company-activity" aria-label="查看更新用户记录" title="查看"><svg class="app-icon app-icon--line" aria-hidden="true"><use href="icons.svg#icon-eye"></use></svg></button></td></tr>
      <tr data-company-activity-row data-search="管理员 文件 上传 产品使用手册" data-activity-result="success"><td>2026-09-03 10:18</td><td>管理员</td><td>文件资料</td><td>上传文件</td><td>产品使用手册 2026.pdf</td><td><span class="status status--online">成功</span></td><td class="mono">192.168.1.20</td><td class="table-actions"><button class="icon-button table-action-button" type="button" data-action="view-company-activity" aria-label="查看上传文件记录" title="查看"><svg class="app-icon app-icon--line" aria-hidden="true"><use href="icons.svg#icon-eye"></use></svg></button></td></tr>
      <tr data-company-activity-row data-search="王工 集成 同步 飞书会议" data-activity-result="failed"><td>2026-09-03 09:52</td><td>王工</td><td>集成配置</td><td>同步数据</td><td>飞书会议</td><td><span class="status status--offline">失败</span></td><td class="mono">192.168.1.64</td><td class="table-actions"><button class="icon-button table-action-button" type="button" data-action="view-company-activity" aria-label="查看同步失败记录" title="查看"><svg class="app-icon app-icon--line" aria-hidden="true"><use href="icons.svg#icon-eye"></use></svg></button></td></tr>
      <tr data-company-activity-row data-search="管理员 公司 更新 公司资料" data-activity-result="success"><td>2026-09-02 18:40</td><td>管理员</td><td>公司资料</td><td>更新资料</td><td>德恩基平台公司</td><td><span class="status status--online">成功</span></td><td class="mono">192.168.1.20</td><td class="table-actions"><button class="icon-button table-action-button" type="button" data-action="view-company-activity" aria-label="查看更新公司资料记录" title="查看"><svg class="app-icon app-icon--line" aria-hidden="true"><use href="icons.svg#icon-eye"></use></svg></button></td></tr>
      <tr class="company-activity-empty" data-company-activity-empty hidden><td colspan="8">没有符合条件的操作记录</td></tr>
    </tbody></table>
  </div>
  <footer class="content-card__footer"><span data-company-activity-count>第 1–4 条，共 4 条</span><nav class="pagination" aria-label="操作记录分页"><button type="button" disabled aria-label="上一页"><svg class="app-icon app-icon--line" aria-hidden="true"><use href="icons.svg#icon-chevron-left"></use></svg></button><button class="is-current" type="button" aria-current="page">1</button><button type="button" disabled aria-label="下一页"><svg class="app-icon app-icon--line" aria-hidden="true"><use href="icons.svg#icon-chevron-right"></use></svg></button></nav></footer>
</section>
