<!-- .tpl prevents Live Server from injecting reload scripts into fetched partials. -->
<!-- Handoff: map this list to /api/v1/meeting-integrations and always constrain owner_company_id to the current writable company. Never expose credentials_ciphertext. -->
<div class="company-panel__heading">
  <div><h3>集成配置</h3><p>管理本公司的第三方服务连接与数据同步。</p></div>
  <button class="button button--secondary button--icon-only" type="button" data-action="create-company-integration" aria-label="新增集成" title="新增集成"><svg class="app-icon app-icon--line" aria-hidden="true"><use href="icons.svg#icon-plus"></use></svg></button>
</div>

<section class="content-card company-integrations-card" aria-label="集成配置列表">
  <form class="filter-bar" action="#" data-company-integration-filter>
    <label class="search-field"><span class="sr-only">搜索集成</span><svg class="app-icon app-icon--fill" aria-hidden="true"><use href="icons.svg#icon-search"></use></svg><input type="search" placeholder="搜索名称或服务商" data-company-integration-search></label>
    <label class="select-field"><span class="sr-only">连接状态</span><select data-company-integration-status><option value="">全部状态</option><option value="connected">已连接</option><option value="degraded">异常</option><option value="disabled">已停用</option><option value="untested">未测试</option></select><svg class="app-icon app-icon--fill select-field__icon" aria-hidden="true"><use href="icons.svg#icon-chevron-down"></use></svg></label>
  </form>
  <div class="table-scroll company-integrations-table" role="region" aria-label="集成配置列表，可横向滚动" tabindex="0">
    <table data-sortable-table><thead><tr><th scope="col">连接名称</th><th scope="col">服务商</th><th scope="col">同步方向</th><th scope="col">状态</th><th scope="col">最近同步</th><th scope="col" class="table-actions">操作</th></tr></thead><tbody>
      <tr data-company-integration-row data-search="企业微信会议 wecom" data-integration-status="connected"><td><strong>企业微信会议</strong></td><td>WeCom</td><td>双向同步</td><td><span class="status status--online">已连接</span></td><td>2026-09-03 10:26</td><td class="table-actions"><button class="icon-button table-action-button" type="button" data-action="test-company-integration" data-integration-name="企业微信会议" aria-label="测试企业微信会议连接" title="测试连接"><svg class="app-icon app-icon--line" aria-hidden="true"><use href="icons.svg#icon-check"></use></svg></button><button class="icon-button table-action-button" type="button" data-action="sync-company-integration" data-integration-name="企业微信会议" aria-label="同步企业微信会议" title="立即同步"><svg class="app-icon app-icon--fill" aria-hidden="true"><use href="icons.svg#icon-arrow-clockwise"></use></svg></button><button class="icon-button table-action-button" type="button" aria-label="编辑企业微信会议" title="编辑"><svg class="app-icon app-icon--line" aria-hidden="true"><use href="icons.svg#icon-pencil"></use></svg></button></td></tr>
      <tr data-company-integration-row data-search="飞书会议 feishu" data-integration-status="degraded"><td><strong>飞书会议</strong></td><td>Feishu</td><td>仅导入</td><td><span class="status status--offline">异常</span></td><td>2026-09-03 09:52</td><td class="table-actions"><button class="icon-button table-action-button" type="button" data-action="test-company-integration" data-integration-name="飞书会议" aria-label="测试飞书会议连接" title="测试连接"><svg class="app-icon app-icon--line" aria-hidden="true"><use href="icons.svg#icon-check"></use></svg></button><button class="icon-button table-action-button" type="button" data-action="sync-company-integration" data-integration-name="飞书会议" aria-label="同步飞书会议" title="立即同步"><svg class="app-icon app-icon--fill" aria-hidden="true"><use href="icons.svg#icon-arrow-clockwise"></use></svg></button><button class="icon-button table-action-button" type="button" aria-label="编辑飞书会议" title="编辑"><svg class="app-icon app-icon--line" aria-hidden="true"><use href="icons.svg#icon-pencil"></use></svg></button></td></tr>
      <tr data-company-integration-row data-search="钉钉会议 dingtalk" data-integration-status="disabled"><td><strong>钉钉会议</strong></td><td>DingTalk</td><td>仅导入</td><td><span class="status status--inactive">已停用</span></td><td>2026-08-28 17:10</td><td class="table-actions"><button class="icon-button table-action-button" type="button" data-action="test-company-integration" data-integration-name="钉钉会议" aria-label="测试钉钉会议连接" title="测试连接"><svg class="app-icon app-icon--line" aria-hidden="true"><use href="icons.svg#icon-check"></use></svg></button><button class="icon-button table-action-button" type="button" aria-label="编辑钉钉会议" title="编辑"><svg class="app-icon app-icon--line" aria-hidden="true"><use href="icons.svg#icon-pencil"></use></svg></button></td></tr>
      <tr class="company-integrations-empty" data-company-integrations-empty hidden><td colspan="6">没有符合条件的集成配置</td></tr>
    </tbody></table>
  </div>
  <footer class="content-card__footer"><span data-company-integration-count>第 1–3 条，共 3 条</span><nav class="pagination" aria-label="集成配置分页"><button type="button" disabled aria-label="上一页"><svg class="app-icon app-icon--line" aria-hidden="true"><use href="icons.svg#icon-chevron-left"></use></svg></button><button class="is-current" type="button" aria-current="page">1</button><button type="button" disabled aria-label="下一页"><svg class="app-icon app-icon--line" aria-hidden="true"><use href="icons.svg#icon-chevron-right"></use></svg></button></nav></footer>
</section>
