import http from './http'

export const fetchDeviceEnrollments = (params = {}) => http.get('/device-enrollments', { params })
export const fetchDeviceEnrollmentSummary = () => http.get('/device-enrollments/summary')
export const fetchDeviceEnrollment = uuid => http.get(`/device-enrollments/${uuid}`)
export const fetchDeviceEnrollmentPresence = uuid => http.get(`/device-enrollments/${uuid}/presence`)
export const fetchDeviceEnrollmentPresences = enrollmentUuids => http.post('/device-enrollments/presence/batch', { enrollment_uuids: enrollmentUuids })
export const rematchDeviceEnrollment = uuid => http.post(`/device-enrollments/${uuid}/rematch`)
export const preflightDeviceEnrollment = (uuid, data) => http.post(`/device-enrollments/${uuid}/preflight`, data)
export const claimDeviceEnrollment = (uuid, data) => http.post(`/device-enrollments/${uuid}/claim`, data)
export const confirmDeviceReplacement = (uuid, data) => http.post(`/device-enrollments/${uuid}/confirm-replacement`, data)
export const quarantineDeviceEnrollment = (uuid, reason) => http.post(`/device-enrollments/${uuid}/quarantine`, { reason })
export const releaseDeviceEnrollment = (uuid, reason) => http.post(`/device-enrollments/${uuid}/release`, { reason })
export const revokeDeviceEnrollment = (uuid, reason) => http.post(`/device-enrollments/${uuid}/revoke`, { reason })

export const fetchFactoryRegistry = (params = {}) => http.get('/device-factory-registry', { params })
export const fetchFactoryRegistryReadiness = () => http.get('/device-factory-registry/readiness')
export const fetchFactoryAttestationStatus = serial => http.get('/device-factory-registry/attestation-status', { params: { serial } })
export const issueFactorySerial = () => http.post('/device-factory-registry/serials/next')
export const createFactoryRegistry = data => http.post('/device-factory-registry', data)
export const bulkCreateFactoryRegistry = items => http.post('/device-factory-registry/bulk', { items })
export const updateFactoryRegistry = (uuid, data) => http.put(`/device-factory-registry/${uuid}`, data)
export const revokeFactoryRegistry = (uuid, reason) => http.post(`/device-factory-registry/${uuid}/revoke`, { reason })
export const reactivateFactoryRegistry = (uuid, reason) => http.post(`/device-factory-registry/${uuid}/reactivate`, { reason })
export const recoverUnactivatedFactoryRegistry = (uuid, data) => http.post(`/device-factory-registry/${uuid}/recover-unactivated`, data)
export const confirmFactoryRegistryRepairRekey = (uuid, data) => http.post(`/device-factory-registry/${uuid}/confirm-repair-rekey`, data)

export const fetchFactoryStations = () => http.get('/factory-stations')
export const createFactoryStation = data => http.post('/factory-stations', data)
export const revokeFactoryStation = uuid => http.post(`/factory-stations/${uuid}/revoke`)

export const fetchFactoryBatches = (params = {}) => http.get('/factory-batches', { params })
export const createFactoryBatch = data => http.post('/factory-batches', data)
export const updateFactoryBatch = (uuid, data) => http.put(`/factory-batches/${uuid}`, data)
